name: tiktoktest
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  beamer: ^1.5.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.4
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.9
  http: ^1.1.2
  image_picker: ^1.0.5
  injectable: ^2.3.2
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
