// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQkM3X-d6qhz5zYrgPpU50IOKbzhj5ZRM',
    appId: '1:407457762250:web:aaa7ea5f823460c20d5d33',
    messagingSenderId: '407457762250',
    projectId: 'tiktok-7f877',
    authDomain: 'tiktok-7f877.firebaseapp.com',
    storageBucket: 'tiktok-7f877.appspot.com',
    measurementId: 'G-XSLQ3B3WYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsn55zWzsNAs8JT67VcGpmW4-5vpA2sCE',
    appId: '1:407457762250:android:7d540f37e436d9ce0d5d33',
    messagingSenderId: '407457762250',
    projectId: 'tiktok-7f877',
    storageBucket: 'tiktok-7f877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArKZJf3pVWkAOeLbwU0XWVwIRmaiSmq0o',
    appId: '1:407457762250:ios:84fa508e50d73e860d5d33',
    messagingSenderId: '407457762250',
    projectId: 'tiktok-7f877',
    storageBucket: 'tiktok-7f877.appspot.com',
    androidClientId: '407457762250-t8759eourdv0e45mju9tja7eeqk6r1nm.apps.googleusercontent.com',
    iosClientId: '407457762250-qlq43pgr5698dmipd3icjh22di6usbd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktoktest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArKZJf3pVWkAOeLbwU0XWVwIRmaiSmq0o',
    appId: '1:407457762250:ios:9f08ccdcc09dcc2b0d5d33',
    messagingSenderId: '407457762250',
    projectId: 'tiktok-7f877',
    storageBucket: 'tiktok-7f877.appspot.com',
    androidClientId: '407457762250-t8759eourdv0e45mju9tja7eeqk6r1nm.apps.googleusercontent.com',
    iosClientId: '407457762250-jngb4t6ar96qpok7r9eifcc1u7iikfju.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktoktest.RunnerTests',
  );
}
